# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /src/CMakeFiles /src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gen_db

# Build rule for target.
gen_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_db
.PHONY : gen_db

# fast build rule for target.
gen_db/fast:
	$(MAKE) -f CMakeFiles/gen_db.dir/build.make CMakeFiles/gen_db.dir/build
.PHONY : gen_db/fast

#=============================================================================
# Target rules for targets named tg2sip

# Build rule for target.
tg2sip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tg2sip
.PHONY : tg2sip

# fast build rule for target.
tg2sip/fast:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/build
.PHONY : tg2sip/fast

#=============================================================================
# Target rules for targets named libtgvoip

# Build rule for target.
libtgvoip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtgvoip
.PHONY : libtgvoip

# fast build rule for target.
libtgvoip/fast:
	$(MAKE) -f libtgvoip/CMakeFiles/libtgvoip.dir/build.make libtgvoip/CMakeFiles/libtgvoip.dir/build
.PHONY : libtgvoip/fast

tg2sip/gateway.o: tg2sip/gateway.cpp.o

.PHONY : tg2sip/gateway.o

# target to build an object file
tg2sip/gateway.cpp.o:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/gateway.cpp.o
.PHONY : tg2sip/gateway.cpp.o

tg2sip/gateway.i: tg2sip/gateway.cpp.i

.PHONY : tg2sip/gateway.i

# target to preprocess a source file
tg2sip/gateway.cpp.i:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/gateway.cpp.i
.PHONY : tg2sip/gateway.cpp.i

tg2sip/gateway.s: tg2sip/gateway.cpp.s

.PHONY : tg2sip/gateway.s

# target to generate assembly for a file
tg2sip/gateway.cpp.s:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/gateway.cpp.s
.PHONY : tg2sip/gateway.cpp.s

tg2sip/gen_db.o: tg2sip/gen_db.cpp.o

.PHONY : tg2sip/gen_db.o

# target to build an object file
tg2sip/gen_db.cpp.o:
	$(MAKE) -f CMakeFiles/gen_db.dir/build.make CMakeFiles/gen_db.dir/tg2sip/gen_db.cpp.o
.PHONY : tg2sip/gen_db.cpp.o

tg2sip/gen_db.i: tg2sip/gen_db.cpp.i

.PHONY : tg2sip/gen_db.i

# target to preprocess a source file
tg2sip/gen_db.cpp.i:
	$(MAKE) -f CMakeFiles/gen_db.dir/build.make CMakeFiles/gen_db.dir/tg2sip/gen_db.cpp.i
.PHONY : tg2sip/gen_db.cpp.i

tg2sip/gen_db.s: tg2sip/gen_db.cpp.s

.PHONY : tg2sip/gen_db.s

# target to generate assembly for a file
tg2sip/gen_db.cpp.s:
	$(MAKE) -f CMakeFiles/gen_db.dir/build.make CMakeFiles/gen_db.dir/tg2sip/gen_db.cpp.s
.PHONY : tg2sip/gen_db.cpp.s

tg2sip/logging.o: tg2sip/logging.cpp.o

.PHONY : tg2sip/logging.o

# target to build an object file
tg2sip/logging.cpp.o:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/logging.cpp.o
.PHONY : tg2sip/logging.cpp.o

tg2sip/logging.i: tg2sip/logging.cpp.i

.PHONY : tg2sip/logging.i

# target to preprocess a source file
tg2sip/logging.cpp.i:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/logging.cpp.i
.PHONY : tg2sip/logging.cpp.i

tg2sip/logging.s: tg2sip/logging.cpp.s

.PHONY : tg2sip/logging.s

# target to generate assembly for a file
tg2sip/logging.cpp.s:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/logging.cpp.s
.PHONY : tg2sip/logging.cpp.s

tg2sip/main.o: tg2sip/main.cpp.o

.PHONY : tg2sip/main.o

# target to build an object file
tg2sip/main.cpp.o:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/main.cpp.o
.PHONY : tg2sip/main.cpp.o

tg2sip/main.i: tg2sip/main.cpp.i

.PHONY : tg2sip/main.i

# target to preprocess a source file
tg2sip/main.cpp.i:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/main.cpp.i
.PHONY : tg2sip/main.cpp.i

tg2sip/main.s: tg2sip/main.cpp.s

.PHONY : tg2sip/main.s

# target to generate assembly for a file
tg2sip/main.cpp.s:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/main.cpp.s
.PHONY : tg2sip/main.cpp.s

tg2sip/settings.o: tg2sip/settings.cpp.o

.PHONY : tg2sip/settings.o

# target to build an object file
tg2sip/settings.cpp.o:
	$(MAKE) -f CMakeFiles/gen_db.dir/build.make CMakeFiles/gen_db.dir/tg2sip/settings.cpp.o
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/settings.cpp.o
.PHONY : tg2sip/settings.cpp.o

tg2sip/settings.i: tg2sip/settings.cpp.i

.PHONY : tg2sip/settings.i

# target to preprocess a source file
tg2sip/settings.cpp.i:
	$(MAKE) -f CMakeFiles/gen_db.dir/build.make CMakeFiles/gen_db.dir/tg2sip/settings.cpp.i
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/settings.cpp.i
.PHONY : tg2sip/settings.cpp.i

tg2sip/settings.s: tg2sip/settings.cpp.s

.PHONY : tg2sip/settings.s

# target to generate assembly for a file
tg2sip/settings.cpp.s:
	$(MAKE) -f CMakeFiles/gen_db.dir/build.make CMakeFiles/gen_db.dir/tg2sip/settings.cpp.s
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/settings.cpp.s
.PHONY : tg2sip/settings.cpp.s

tg2sip/sip.o: tg2sip/sip.cpp.o

.PHONY : tg2sip/sip.o

# target to build an object file
tg2sip/sip.cpp.o:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/sip.cpp.o
.PHONY : tg2sip/sip.cpp.o

tg2sip/sip.i: tg2sip/sip.cpp.i

.PHONY : tg2sip/sip.i

# target to preprocess a source file
tg2sip/sip.cpp.i:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/sip.cpp.i
.PHONY : tg2sip/sip.cpp.i

tg2sip/sip.s: tg2sip/sip.cpp.s

.PHONY : tg2sip/sip.s

# target to generate assembly for a file
tg2sip/sip.cpp.s:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/sip.cpp.s
.PHONY : tg2sip/sip.cpp.s

tg2sip/tg.o: tg2sip/tg.cpp.o

.PHONY : tg2sip/tg.o

# target to build an object file
tg2sip/tg.cpp.o:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/tg.cpp.o
.PHONY : tg2sip/tg.cpp.o

tg2sip/tg.i: tg2sip/tg.cpp.i

.PHONY : tg2sip/tg.i

# target to preprocess a source file
tg2sip/tg.cpp.i:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/tg.cpp.i
.PHONY : tg2sip/tg.cpp.i

tg2sip/tg.s: tg2sip/tg.cpp.s

.PHONY : tg2sip/tg.s

# target to generate assembly for a file
tg2sip/tg.cpp.s:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/tg.cpp.s
.PHONY : tg2sip/tg.cpp.s

tg2sip/utils.o: tg2sip/utils.cpp.o

.PHONY : tg2sip/utils.o

# target to build an object file
tg2sip/utils.cpp.o:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/utils.cpp.o
.PHONY : tg2sip/utils.cpp.o

tg2sip/utils.i: tg2sip/utils.cpp.i

.PHONY : tg2sip/utils.i

# target to preprocess a source file
tg2sip/utils.cpp.i:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/utils.cpp.i
.PHONY : tg2sip/utils.cpp.i

tg2sip/utils.s: tg2sip/utils.cpp.s

.PHONY : tg2sip/utils.s

# target to generate assembly for a file
tg2sip/utils.cpp.s:
	$(MAKE) -f CMakeFiles/tg2sip.dir/build.make CMakeFiles/tg2sip.dir/tg2sip/utils.cpp.s
.PHONY : tg2sip/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gen_db"
	@echo "... rebuild_cache"
	@echo "... tg2sip"
	@echo "... libtgvoip"
	@echo "... tg2sip/gateway.o"
	@echo "... tg2sip/gateway.i"
	@echo "... tg2sip/gateway.s"
	@echo "... tg2sip/gen_db.o"
	@echo "... tg2sip/gen_db.i"
	@echo "... tg2sip/gen_db.s"
	@echo "... tg2sip/logging.o"
	@echo "... tg2sip/logging.i"
	@echo "... tg2sip/logging.s"
	@echo "... tg2sip/main.o"
	@echo "... tg2sip/main.i"
	@echo "... tg2sip/main.s"
	@echo "... tg2sip/settings.o"
	@echo "... tg2sip/settings.i"
	@echo "... tg2sip/settings.s"
	@echo "... tg2sip/sip.o"
	@echo "... tg2sip/sip.i"
	@echo "... tg2sip/sip.s"
	@echo "... tg2sip/tg.o"
	@echo "... tg2sip/tg.i"
	@echo "... tg2sip/tg.s"
	@echo "... tg2sip/utils.o"
	@echo "... tg2sip/utils.i"
	@echo "... tg2sip/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

